name: Deploy to Test Worker

on:
  push:
    branches:
      - site-test   # only runs when you push to site-test
  workflow_dispatch: # lets you trigger manually

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with Wrangler (direct)
        run: npx wrangler whoami
        env:
             CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
             CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

